name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        echo "Deploying to VM"
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
          # Navigate to your app directory
          cd /home/falcon/fastapi-book-project || exit 1
          
          git pull origin main || exit 1

          docker build -t fastapi-book-project . || exit 1
          
          docker run --network host --restart always -d fastapi-book-project || exit 1
        EOF
